/**
 * SendX API
 * SendX is built on the simple tenet that users must have open access to their data. SendX API is the first step in that direction. To cite some examples:   - subscribe / unsubscribe a contact from a list   - Schedule campaign to a segment of users   - Trigger transactional emails   - Get / PUT / POST and DELETE operations on team, campaign, list, contact, report etc. and so on.  As companies grow big, custom use cases around email marketing also crop up. SendX API ensures that SendX platform is able to satisfy such unforeseen use cases. They may range from building custom reporting dashboard to tagging contacts with custom attributes or triggering emails based on recommendation algorithm.  We do our best to have all our URLs be [RESTful](http://en.wikipedia.org/wiki/Representational_state_transfer). Every endpoint (URL) may support one of four different http verbs. GET requests fetch information about an object, POST requests create objects, PUT requests update objects, and finally DELETE requests will delete objects.  Also all API calls besides:   - Subscribe / unsubscribe signup form required **api_key** to be passed as **header**   ### The Envelope Every response is contained by an envelope. That is, each response has a predictable set of keys with which you can expect to interact: ```json {     \"status\": \"200\",     \"message\": \"OK\",     \"data\"\": [        {          ...        },        .        .        .     ] } ```  #### Status The status key is used to communicate extra information about the response to the developer. If all goes well, you'll only ever see a code key with value 200. However, sometimes things go wrong, and in that case you might see a response like: ```json {     \"status\": \"404\" } ```  #### Data The data key is the meat of the response. It may be a list containing single object or multiple objects  #### Message This returns back human readable message. This is specially useful to make sense in case of error scenarios. 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BulkContact;
import io.swagger.client.model.InlineResponse2005;
import io.swagger.client.model.ContactCustomfield;
import io.swagger.client.model.Contact;
import io.swagger.client.model.ContactAddUpdate;
import io.swagger.client.model.InlineResponse2002;
import io.swagger.client.model.InlineResponse2003;
import io.swagger.client.model.InlineResponse2004;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ContactApi
 */
public class ContactApiTest {

    private final ContactApi api = new ContactApi();

    
    /**
     * Add a bulk of contacts in a request
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void contactBulkPostTest() throws ApiException {
        String apiKey = null;
        BulkContact body = null;
        // api.contactBulkPost(apiKey, body);

        // TODO: test validations
    }
    
    /**
     * Add Customfield data for a contact
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void contactContactIdCustomfieldPostTest() throws ApiException {
        String apiKey = null;
        Long contactId = null;
        ContactCustomfield body = null;
        // InlineResponse2005 response = api.contactContactIdCustomfieldPost(apiKey, contactId, body);

        // TODO: test validations
    }
    
    /**
     * Deletes a contact
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void contactContactIdDeleteTest() throws ApiException {
        String apiKey = null;
        Long contactId = null;
        // api.contactContactIdDelete(apiKey, contactId);

        // TODO: test validations
    }
    
    /**
     * Find contact by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void contactContactIdGetTest() throws ApiException {
        String apiKey = null;
        Long contactId = null;
        // Contact response = api.contactContactIdGet(apiKey, contactId);

        // TODO: test validations
    }
    
    /**
     * Update a contact by ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void contactContactIdPutTest() throws ApiException {
        String apiKey = null;
        Long contactId = null;
        ContactAddUpdate body = null;
        // InlineResponse2002 response = api.contactContactIdPut(apiKey, contactId, body);

        // TODO: test validations
    }
    
    /**
     * Get information about all contacts
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void contactGetTest() throws ApiException {
        String apiKey = null;
        Integer limit = null;
        Integer offset = null;
        // InlineResponse2003 response = api.contactGet(apiKey, limit, offset);

        // TODO: test validations
    }
    
    /**
     * Add a new contact
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void contactPostTest() throws ApiException {
        String apiKey = null;
        ContactAddUpdate body = null;
        // InlineResponse2004 response = api.contactPost(apiKey, body);

        // TODO: test validations
    }
    
}
